version: '3.9'

services:

  # ZIPKIN
  zipkin-server:
    image: openzipkin/zipkin:2.23.8
    ports:
      - 9411:9411
    restart: always
    networks:
      - jave-network

  # NAMING SERVER
  naming-server:
    image: henrick182/jave-naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - jave-network
      
  # API GATEWAY
  api-gateway:
    image: henrick182/jave-api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.TRACING.SAMPLING.PROBABILITY: 1.0
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
    networks:
      - jave-network

networks:
  jave-network:
    driver: bridge
