ALTER TABLE `software` ADD COLUMN FK_USER_LAST_UPDATE INT NOT NULL DEFAULT 1;

ALTER TABLE `software` ADD COLUMN LAST_UPDATE_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE `software` ADD COLUMN FK_USER_CREATION INT NOT NULL DEFAULT 1;

ALTER TABLE `software` ADD COLUMN CREATION_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE `software` ADD CONSTRAINT FK_USER_SOFTWARE_LAST_UPDATE
FOREIGN KEY (FK_USER_LAST_UPDATE)
REFERENCES `users` (ID);

ALTER TABLE `software` ADD CONSTRAINT FK_USER_SOFTWARE_CREATION
FOREIGN KEY (FK_USER_CREATION)
REFERENCES `users` (ID);
