CREATE TABLE IF NOT EXISTS `knowledge` (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100) DEFAULT NULL,
    FK_SOFTWARE INT NOT NULL,
    CONTENT TEXT NOT NULL
);
 
ALTER TABLE `knowledge` ADD CONSTRAINT FK_SOFTWARE_KNOWLEDGE
    FOREIGN KEY (FK_SOFTWARE)
    REFERENCES `software` (ID);
