CREATE TABLE `knowledge_topic` (
    FK_KNOWLEDGE INT NOT NULL,
    FK_TOPIC INT NOT NULL
);
 
ALTER TABLE `knowledge_topic` ADD CONSTRAINT FK_KNOWLEDGE_KNOWLEDGETOPIC
    FOREIGN KEY (FK_KNOWLEDGE)
    REFERENCES KNOWLEDGE (ID);
 
ALTER TABLE `knowledge_topic` ADD CONSTRAINT FK_TOPIC_KNOWLEDGETOPIC
    FOREIGN KEY (FK_TOPIC)
    REFERENCES TOPIC (ID);
