CREATE TABLE IF NOT EXISTS `users` (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) UNIQUE DEFAULT NULL,
    FULL_NAME VARCHAR(255) DEFAULT NULL,
    PASSWORD VARCHAR(255) DEFAULT NULL,
    ACCOUNT_NON_EXPIRED TINYINT DEFAULT TRUE,
    ACCOUNT_NON_LOCKED TINYINT DEFAULT TRUE,
    CREDENTIALS_NON_EXPIRED TINYINT DEFAULT TRUE,
    ENABLED TINYINT DEFAULT TRUE
);