CREATE TABLE IF NOT EXISTS `user_permission` (
    ID_USER INT,
    ID_PERMISSION INT,
    PRIMARY KEY (ID_USER, ID_PERMISSION)
);

ALTER TABLE `user_permission` ADD CONSTRAINT FK_USERS_USERPERMISSION
    FOREIGN KEY (ID_USER)
    REFERENCES `users` (ID);
 
ALTER TABLE `user_permission` ADD CONSTRAINT FK_PERMISSION_USERPERMISSION
    FOREIGN KEY (ID_PERMISSION)
    REFERENCES `permission` (ID);