CREATE TABLE USER_PERMISSION (
    ID_USER INT,
    ID_PERMISSION INT,
    PRIMARY KEY (ID_USER, ID_PERMISSION)
);

ALTER TABLE USER_PERMISSION ADD CONSTRAINT FK_USERS_USERPERMISSION
    FOREIGN KEY (ID_USER)
    REFERENCES USERS (ID);
 
ALTER TABLE USER_PERMISSION ADD CONSTRAINT FK_PERMISSION_USERPERMISSION
    FOREIGN KEY (ID_PERMISSION)
    REFERENCES PERMISSION (ID);