CREATE TABLE `company_software` (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FK_COMPANY INT DEFAULT NULL,
    FK_SOFTWARE INT NOT NULL,
    TYPE ENUM('GERAL', 'FISCAL') NOT NULL,
    HAVE_AUTHORIZATION TINYINT NOT NULL,
    `CONNECTION` VARCHAR(100) NOT NULL,
    OBSERVATION VARCHAR(100) NOT NULL,
    IS_ACTIVE TINYINT DEFAULT TRUE,
    FK_COMPANY_SOFTWARE_SAME_DB INT DEFAULT NULL
);

ALTER TABLE `company_software` ADD CONSTRAINT FK_SOFTWARE_COMPANYSOFTWARE
    FOREIGN KEY (FK_SOFTWARE)
    REFERENCES `software` (ID);
 
ALTER TABLE `company_software` ADD CONSTRAINT FK_COMPANY_COMPANYSOFTWARE
    FOREIGN KEY (FK_COMPANY)
    REFERENCES `company` (ID);
 
ALTER TABLE `company_software` ADD CONSTRAINT FK_COMPANYSOFTWARE_SAME_DB
    FOREIGN KEY (FK_COMPANY_SOFTWARE_SAME_DB)
    REFERENCES `company_software` (ID);