ALTER TABLE `company` DROP COLUMN HAVE_AUTHORIZATION;
ALTER TABLE `company` DROP COLUMN SOFTWARE;
ALTER TABLE `company` DROP COLUMN `CONNECTION`;
ALTER TABLE `company` DROP CONSTRAINT FK_COMPANY_COMPANY_SAME_DB;
ALTER TABLE `company` DROP COLUMN FK_COMPANY_SAME_DB;

UPDATE `company` SET observation = '';