ALTER TABLE `ibpt_update` RENAME `ibpt`;

ALTER TABLE `ibpt` DROP CONSTRAINT FK_COMPANY_IBPTUPDATE;
ALTER TABLE `ibpt` DROP CONSTRAINT FK_VERSION_IBPTUPDATE;
ALTER TABLE `ibpt` DROP CONSTRAINT UNIQUE_IBPTUPDATE;

ALTER TABLE `ibpt` CHANGE COLUMN FK_COMPANY FK_COMPANY_SOFTWARE INT NOT NULL;

ALTER TABLE `ibpt` ADD CONSTRAINT FK_VERSION_IBPT
	FOREIGN KEY (FK_VERSION)
    REFERENCES `version` (ID);
    
ALTER TABLE `ibpt` ADD CONSTRAINT FK_COMPANYSOFTWARE_IBPT
	FOREIGN KEY (FK_COMPANY_SOFTWARE)
    REFERENCES `company_software` (ID);
    
ALTER TABLE `ibpt` ADD CONSTRAINT `UNIQUE_IBPT` UNIQUE KEY (`FK_COMPANY_SOFTWARE`, `FK_VERSION`);