DROP PROCEDURE `PROC_NEW_IBPT_UPDATE`;

DELIMITER $$
CREATE PROCEDURE `PROC_NEW_IBPT`(P_ID_VERSION INT)
    COMMENT ''
BEGIN
	INSERT INTO `ibpt`(FK_VERSION, FK_COMPANY_SOFTWARE, IS_UPDATED)
	     SELECT P_ID_VERSION, COSO.ID, FALSE
	       FROM `company_software` COSO
     INNER JOIN `company` COMP ON COSO.FK_COMPANY = COMP.ID
	      WHERE COMP.IS_ACTIVE = 1 
	        AND ((SELECT COUNT(*) FROM `ibpt` IBPT WHERE IBPT.FK_VERSION = P_ID_VERSION and IBPT.FK_COMPANY_SOFTWARE = COSO.ID ) = 0)
            AND COSO.`TYPE` = 'FISCAL'
            AND COSO.IS_ACTIVE = 1;
END
$$
DELIMITER ;