ALTER TABLE `ibpt` ADD COLUMN FK_USER_LAST_UPDATE INT DEFAULT NULL;

ALTER TABLE `ibpt` ADD COLUMN LAST_UPDATE_DATETIME DATETIME DEFAULT NULL;

ALTER TABLE `ibpt` ADD COLUMN FK_USER_CREATION INT NOT NULL DEFAULT 1;

ALTER TABLE `ibpt` ADD COLUMN CREATION_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE `ibpt` ADD CONSTRAINT FK_USER_IBPT_LAST_UPDATE
FOREIGN KEY (FK_USER_LAST_UPDATE)
REFERENCES `users` (ID);

ALTER TABLE `ibpt` ADD CONSTRAINT FK_USER_IBPT_CREATION
FOREIGN KEY (FK_USER_CREATION)
REFERENCES `users` (ID);
