CREATE TABLE KNOWLEDGE (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR DEFAULT NULL,
    FK_SOFTWARE INT,
    CONTENT TEXT NOT NULL
);
 
ALTER TABLE KNOWLEDGE ADD CONSTRAINT FK_SOFTWARE_KNOWLEDGE
    FOREIGN KEY (FK_SOFTWARE)
    REFERENCES SOFTWARE (ID);
