CREATE TABLE KNOWLEDGEMENT_TOPIC (
    FK_KNOWLEDGE INT NOT NULL,
    FK_TOPIC INT NOT NULL
);
 
ALTER TABLE KNOWLEDGEMENT_TOPIC ADD CONSTRAINT FK_KNOWLEDGE_KNOWLEDGETOPIC
    FOREIGN KEY (FK_KNOWLEDGE)
    REFERENCES KNOWLEDGE (ID);
 
ALTER TABLE KNOWLEDGEMENT_TOPIC ADD CONSTRAINT FK_TOPIC_KNOWLEDGETOPIC
    FOREIGN KEY (FK_TOPIC)
    REFERENCES TOPIC (ID);
