DELIMITER $$
CREATE PROCEDURE `PROC_NEW_IBPT_UPDATE`()
    COMMENT ''
BEGIN
	DECLARE V_ID_VERSION INT DEFAULT (select ID from VERSION where EFFECTIVE_PERIOD_UNTIL >= curdate());
    
	INSERT INTO IBPT_UPDATE(FK_VERSION, FK_COMPANY)
    SELECT VERS.ID, COMP.ID FROM `VERSION` VERS, COMPANY COMP 
    WHERE VERS.ID = V_ID_VERSION 
    AND COMP.IS_ACTIVE = 1 
    AND ((SELECT COUNT(*) FROM IBPT_UPDATE IUPD WHERE IUPD.FK_VERSION = VERS.ID and IUPD.FK_COMPANY = COMP.ID) = 0);
END
$$
DELIMITER ;