DELIMITER $$
CREATE PROCEDURE `PROC_NEW_IBPT_UPDATE`(P_ID_VERSION INT)
    COMMENT ''
BEGIN
	INSERT INTO IBPT_UPDATE(FK_VERSION, FK_COMPANY)
	     SELECT VERS.ID, COMP.ID 
	       FROM `VERSION` VERS, COMPANY COMP 
	      WHERE VERS.ID = P_ID_VERSION
	        AND COMP.IS_ACTIVE = 1 
	        AND ((SELECT COUNT(*) FROM IBPT_UPDATE IBPD WHERE IBPD.FK_VERSION = VERS.ID and IBPD.FK_COMPANY = COMP.ID ) = 0);
END
$$
DELIMITER ;