DELIMITER $$
CREATE PROCEDURE `PROC_NEW_IBPT_UPDATE`(P_ID_VERSION INT)
    COMMENT ''
BEGIN
	INSERT INTO `ibpt_update`(FK_VERSION, FK_COMPANY)
	     SELECT VERS.ID, COMP.ID 
	       FROM `version` VERS, `company` COMP 
	      WHERE VERS.ID = P_ID_VERSION
	        AND COMP.IS_ACTIVE = 1 
	        AND ((SELECT COUNT(*) FROM `ibpt_update` IBUP WHERE IBUP.FK_VERSION = VERS.ID and IBUP.FK_COMPANY = COMP.ID ) = 0);
END
$$
DELIMITER ;