server:
  port: 8600
cors:
  originPatterns: http://127.0.0.1:9090,http://localhost:8300,http://localhost:8400,http://localhost:8500
files:
  upload-dir: /Server/Files
spring:
  application:
    name: file-service
  jackson:
    time-zone: America/Sao_Paulo
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB
