server:
  port: 8686
files:
  upload-dir: /Server/Files
spring:
  application:
    name: file-service
  jackson:
    time-zone: America/Sao_Paulo
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB
