CREATE TABLE IF NOT EXISTS IBPT.TB_VERSION (
    ID SERIAL PRIMARY KEY,
    NAME CHAR(6) NOT NULL CONSTRAINT UC_NAME UNIQUE,
	EFFECTIVE_PERIOD_FROM DATE NOT NULL,
    EFFECTIVE_PERIOD_UNTIL DATE NOT NULL,
	CONSTRAINT CHK_EFFECTIVE_PERIOD_UNTIL_LARGER_THAN_EFFECTIVE_PERIOD_FROM CHECK(EFFECTIVE_PERIOD_UNTIL > EFFECTIVE_PERIOD_FROM)
);
