CREATE TABLE IF NOT EXISTS IBPT.TB_IBPT (
    ID SERIAL CONSTRAINT PK_TB_IBPT PRIMARY KEY,
    FK_COMPANY_SOFTWARE INT NOT NULL,
    FK_VERSION INT NOT NULL,
    IS_UPDATED BOOLEAN DEFAULT FALSE NOT NULL,
	LAST_UPDATE_DATETIME TIMESTAMP default CURRENT_TIMESTAMP,
	CREATION_DATETIME TIMESTAMP default CURRENT_TIMESTAMP,
    CONSTRAINT UC_FK_COMPANY_SOFTWARE_FK_VERSION UNIQUE (FK_COMPANY_SOFTWARE, FK_VERSION) 
);
 
ALTER TABLE IBPT.TB_IBPT ADD CONSTRAINT FK_COMPANY
    FOREIGN KEY (FK_COMPANY_SOFTWARE)
    REFERENCES SISTEMAS.TB_COMPANY_SOFTWARE (ID);
 
ALTER TABLE IBPT.TB_IBPT ADD CONSTRAINT FK_VERSION
    FOREIGN KEY (FK_VERSION)
    REFERENCES IBPT.TB_VERSION (ID);
