CREATE TABLE IF NOT EXISTS AUTH.TB_USERS (
    ID SERIAL CONSTRAINT PK_TB_USERS PRIMARY KEY,
    USER_NAME VARCHAR(255) CONSTRAINT UC_TB_USERS_USER_NAME UNIQUE NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACCOUNT_NON_EXPIRED BOOLEAN DEFAULT TRUE NOT NULL,
    ACCOUNT_NON_LOCKED BOOLEAN DEFAULT TRUE NOT NULL,
    CREDENTIALS_NON_EXPIRED BOOLEAN DEFAULT TRUE NOT NULL,
    ENABLED BOOLEAN DEFAULT TRUE NOT NULL
);
