CREATE TABLE IF NOT EXISTS AUTH.TB_USER_PERMISSION (
    FK_USER INT,
    FK_PERMISSION INT,
    CONSTRAINT PK_TB_USER_PERMISSION PRIMARY KEY (FK_USER, FK_PERMISSION)
);

ALTER TABLE AUTH.TB_USER_PERMISSION ADD CONSTRAINT FK_USERS
    FOREIGN KEY (FK_USER)
    REFERENCES AUTH.TB_USERS (ID);
 
ALTER TABLE AUTH.TB_USER_PERMISSION ADD CONSTRAINT FK_PERMISSION
    FOREIGN KEY (FK_PERMISSION)
    REFERENCES AUTH.TB_PERMISSION (ID);