CREATE TABLE IF NOT EXISTS SISTEMAS.TB_COMPANY (
    ID SERIAL CONSTRAINT PK_TB_COMPANY PRIMARY KEY,
    CNPJ CHAR(14) NOT NULL CONSTRAINT UQ_TB_COMPANY_CNPJ UNIQUE,
    TRADE_NAME VARCHAR(255) NOT NULL,
    BUSINESS_NAME VARCHAR(255) NOT NULL,
    OBSERVATION VARCHAR(255) DEFAULT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL
);
