server:
  port: 8080
cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  data:
    jdbc:
      repositories:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jave?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  flyway:
    baselineOnMigrate: true
springdoc:
  paths-to-match: 
    - /v1/**
    - /v2/**
    - /auth/**
  swagger-ui: 
    use-root-path: true
