server:
  port: 8080
spring:
  data:
    jdbc:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jave_conhecimento?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 12345678
  flyway:
    baselineOnMigrate: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
springdoc:
  paths-to-match: 
    - /v1/**
  swagger-ui: 
    use-root-path: true
